### PR TITLE
Import doxia-core packages

### LINKED ISSUE #141: Rework class loading for reports with regards to `org.apache.maven.doxia.sink.impl.SinkEventAttributeSet`
### Affected version

2.0.0

### Bug description

The class loading behaviour of reports leads to potentially different versions of doxia-sink-api and doxia-core. Although the latter was initially thought for being used inside Doxia only it was used also in lots of reports (e.g. https://github.com/apache/maven-changes-plugin/blob/6cea480813789a2b366cbc6a7909a50390c493f6/src/main/java/org/apache/maven/plugins/changes/issues/AbstractIssuesReportRenderer.java#L25 or https://github.com/apache/maven-project-info-reports-plugin/blob/ec887bf3f20d0036b9bda5ef5a389b5659cf0952/src/main/java/org/apache/maven/report/projectinfo/DependencyConvergenceReport.java#L306).

If the impl in doxia-core is much older than its API in doxia-sink-api one runs into issue like observed in the context of https://github.com/apache/maven-site-plugin/pull/1245.

### PR DESCRIPTION
**Pull request by kwin**
This prevents version conflicts between doxia-sink-api (always provided by m-site-p) and doxia-core (previously loaded in the version requested via the report)

This closes #141

Following this checklist to help us incorporate your
contribution quickly and easily:

- [ ] Your pull request should address just one issue, without pulling in other changes.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Each commit in the pull request should have a meaningful subject line and body.
  Note that commits might be squashed by a maintainer on merge.
- [ ] Write unit tests that match behavioral changes, where the tests fail if the changes to the runtime are not applied.
  This may not always be possible but is a best-practice.
- [ ] Run `mvn verify` to make sure basic checks pass.
  A more thorough check will be performed on your pull request automatically.
- [ ] You have run the integration tests successfully (`mvn -Prun-its verify`).

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

- [ ] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
- [ ] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Review by michael-o — APPROVED** [review]

File: src/main/java/org/apache/maven/reporting/exec/DefaultMavenReportExecutor.java [hunk 1]
```diff
@@ -111,24 +111,25 @@ public class DefaultMavenReportExecutor implements MavenReportExecutor {
...
+            "org.apache.maven.doxia.sink",
+            "org.apache.maven.doxia.util");
 
+    /**
+     * The following artifacts are provided in the version as referenced in the site plugin (to prevent versions conflicts with the one used by the report plugin).
+     * This must correlate to the list of packages imported in {@link #IMPORTS}.
+     */
     private static final List<String> EXCLUDES =
-            Arrays.asList("doxia-site-renderer", "doxia-sink-api", "maven-reporting-api");
+            Arrays.asList("doxia-sink-api", "doxia-core", "doxia-site-renderer", "maven-reporting-api");
```
Comment (slawekjaranowski) [inline src/main/java/org/apache/maven/reporting/exec/DefaultMavenReportExecutor.java:132]: as maven-reporting-impl can depends on api ... maybe should also be provided?

Comment (slawekjaranowski) [reply src/main/java/org/apache/maven/reporting/exec/DefaultMavenReportExecutor.java:132]: we have the same package in both:
 - https://github.com/apache/maven-reporting-api/tree/master/src/main/java/org/apache/maven/reporting
 - https://github.com/apache/maven-reporting-impl/tree/master/src/main/java/org/apache/maven/reporting

Comment (kwin) [reply src/main/java/org/apache/maven/reporting/exec/DefaultMavenReportExecutor.java:132]: Do you have a concrete example which lead to issues that can be used as IT?

Comment (slawekjaranowski) [reply src/main/java/org/apache/maven/reporting/exec/DefaultMavenReportExecutor.java:132]: not now

Comment (kwin) [reply src/main/java/org/apache/maven/reporting/exec/DefaultMavenReportExecutor.java:132]: Not sure about the impact of EXCLUDES at all since imports are always considered first IIRC or am I wrong here?

Comment (kwin) [reply src/main/java/org/apache/maven/reporting/exec/DefaultMavenReportExecutor.java:132]: "reporting-impl" is not provided by the parent classloader (i.e. the one from m-s-p) therefore cannot be excluded.

**Review by slawekjaranowski — APPROVED** [review]
